Homework 2
================
Sushupta Vijapur

``` r
library(tidyverse)
```

    ## -- Attaching packages --------------------------------- tidyverse 1.3.0 --

    ## v ggplot2 3.3.2     v purrr   0.3.4
    ## v tibble  3.0.3     v dplyr   1.0.2
    ## v tidyr   1.1.2     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.5.0

    ## -- Conflicts ------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

Read in the Mr.Trashwheel dataset

``` r
trashwheel_df = 
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "Mr. Trash Wheel",
  range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

The columns 15-17 were added bc of the unnamed notes column

Read precipitation data 2017 and 2018 and clean.

``` r
precip_2018 = 
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    skip = 1
    ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)

precip_2017 = 
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2017 Precipitation",
    skip = 1
    ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

Now combine precipitation datasets month.names are character vectors
built into R mutate(month = month.name\[month\]) But this is ugly and we
don’t like it Below is a better way.

``` r
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precip_df = 
  bind_rows(precip_2017, precip_2018)

left_join(precip_df, month_df, by = "month")
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2017     1  2.34 January   
    ##  2  2017     2  1.46 February  
    ##  3  2017     3  3.57 March     
    ##  4  2017     4  3.99 April     
    ##  5  2017     5  5.64 May       
    ##  6  2017     6  1.4  June      
    ##  7  2017     7  7.09 July      
    ##  8  2017     8  4.44 August    
    ##  9  2017     9  1.95 September 
    ## 10  2017    10  0    October   
    ## # ... with 14 more rows

This dataset contains information from the Mr.Trashwheel trash collector
in Baltimore Maryland. As trash enters the inner harbor, the trashwheel
collects that trash and stores it in a dumpster. The dataset contains
information on year, month, and trash collected, include some specific
types of trash. There are a total of 344 rows in our final dataset.
Additionally, data sheets include month precipitation data.

## Problem 2

# Part a

Load NYC transit data frame and clean it.

``` r
nyc_transit = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")   %>%
  janitor::clean_names() %>% 
  select(line:route11, entry, vending, entrance_type, ada) %>% 
  mutate(
    entry = recode(entry, "YES" = "TRUE", "NO" = "FALSE"))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

# Part b

Descriptive understanding of the data frame.

``` r
nrow(distinct(nyc_transit, line, station_name))
```

    ## [1] 465

``` r
filter(nyc_transit, ada == "TRUE")
```

    ## # A tibble: 468 x 19
    ##    line  station_name station_latitude station_longitu~ route1 route2 route3
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Av~ Atlantic Av~             40.7            -74.0 B      Q      D     
    ##  2 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  3 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  4 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  5 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  6 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  7 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  8 4 Av~ Pacific St               40.7            -74.0 B      Q      D     
    ##  9 4 Av~ Pacific St               40.7            -74.0 B      Q      D     
    ## 10 42nd~ Grand Centr~             40.8            -74.0 GS     4      5     
    ## # ... with 458 more rows, and 12 more variables: route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entry <chr>, vending <chr>, entrance_type <chr>, ada <lgl>

``` r
filter(nyc_transit, vending == "NO")
```

    ## # A tibble: 183 x 19
    ##    line  station_name station_latitude station_longitu~ route1 route2 route3
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Av~ 53rd St                  40.6            -74.0 R      <NA>   <NA>  
    ##  2 4 Av~ 77th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  3 4 Av~ 9th St                   40.7            -74.0 F      G      R     
    ##  4 4 Av~ Bay Ridge Av             40.6            -74.0 R      <NA>   <NA>  
    ##  5 42nd~ Grand Centr~             40.8            -74.0 GS     4      5     
    ##  6 42nd~ Grand Centr~             40.8            -74.0 GS     4      5     
    ##  7 6 Av~ 7th Av                   40.7            -74.0 F      <NA>   <NA>  
    ##  8 6 Av~ 7th Av                   40.7            -74.0 F      <NA>   <NA>  
    ##  9 6 Av~ 7th Av                   40.7            -74.0 F      <NA>   <NA>  
    ## 10 6 Av~ 7th Av                   40.7            -74.0 F      <NA>   <NA>  
    ## # ... with 173 more rows, and 12 more variables: route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entry <chr>, vending <chr>, entrance_type <chr>, ada <lgl>

This dataset contains information related to each extrance and exit for
each subway station in NYC. There are 1868 in the observations in the
data set and 19 variables. In order to clean the data, I used the
“clean\_names” function in the janitor package to change all variable
naming mechanisms to snake case. Furthermore, I only selected in
relevant variables into the data frame (line, station name, station
latitude / longitude, routes served, entry, vending, entrance type and
ADA compliance). Furthermore, I recoded the entry variable from Yes/No
to a logical as True/False.

While running some descriptives on the dataset, I found that there was
465 distinct stations (defined by both the statio name and the line).
Additionally, I found that there was 468 observations which are ADA
compliant

## Problem 3

Load pols-month csv file.

``` r
pols_month = 
  read_csv("./data/pols-month.csv") %>% 
  separate(mon, into = c("year", "month"), sep = 4) %>% 
  separate(month, into = c("month", "day"), sep = 3) %>% 
  mutate(month = recode(month, "-" = ""))
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )
